import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'package:music_flow_mobile/utils/app_logger.dart';

class YoutubeCaptionService {
  static Future<Map<String, String>?> getYoutubeCaptions(
    YoutubeExplode yt,
    String videoId,
  ) async {
    try {
      AppLogger.info('Fetching youtube captions for $videoId', 'YOUTUBE');
      final manifest = await yt.videos.closedCaptions.getManifest(videoId);
      if (manifest.tracks.isEmpty) return null;

      final result = <String, String>{};

      final relevantTracks = manifest.tracks.where((t) =>
          t.language.code.startsWith('uk') ||
          t.language.code.startsWith('ru') ||
          t.language.code.startsWith('en')).toList();

      if (relevantTracks.isEmpty) {
        relevantTracks.add(manifest.tracks.first);
      }

      relevantTracks.sort((a, b) =>
          a.isAutoGenerated == b.isAutoGenerated ? 0 : (a.isAutoGenerated ? 1 : -1));

      for (var trackInfo in relevantTracks) {
        var track = await yt.videos.closedCaptions.get(trackInfo);

        StringBuffer lrcBuffer = StringBuffer();
        String? currentMergedRaw;
        String? currentMergedLrc;
        Duration? currentMergedStart;
        Duration? lastChunkEnd;

        void flushCurrentLine() {
          if (currentMergedLrc != null && currentMergedStart != null) {
            final minutes = currentMergedStart.inMinutes.toString().padLeft(2, '0');
            final seconds = (currentMergedStart.inSeconds % 60).toString().padLeft(2, '0');
            final ms = (currentMergedStart.inMilliseconds % 1000 ~/ 10).toString().padLeft(2, '0');
            lrcBuffer.writeln('[$minutes:$seconds.$ms] ${currentMergedLrc.trim()}');
          }
        }

        final Duration leadOffset = trackInfo.isAutoGenerated
            ? const Duration(milliseconds: 350)
            : Duration.zero;

        Duration adjustOffset(Duration original) {
          final adjusted = original - leadOffset;
          return adjusted.isNegative ? Duration.zero : adjusted;
        }

        for (var caption in track.captions) {
          var cleanedText = caption.text.replaceAll('\n', ' ');
          cleanedText = cleanedText.replaceAll(RegExp(r'<[^>]*>'), '');
          cleanedText = cleanedText.replaceAll(RegExp(r'\[[^\]]*\]'), '');
          cleanedText = cleanedText.replaceAll(RegExp(r'>>|<<'), '');
          cleanedText = cleanedText.replaceAll(RegExp(r'\s+'), ' ').trim();

          if (cleanedText.isEmpty) continue;

          final effectiveOffset = adjustOffset(caption.offset);
          final min = effectiveOffset.inMinutes.toString().padLeft(2, '0');
          final sec = (effectiveOffset.inSeconds % 60).toString().padLeft(2, '0');
          final msec = (effectiveOffset.inMilliseconds % 1000 ~/ 10).toString().padLeft(2, '0');
          final timeTag = '<$min:$sec.$msec>';

          if (currentMergedRaw == null) {
            currentMergedRaw = cleanedText;
            currentMergedLrc = '$timeTag $cleanedText';
            currentMergedStart = effectiveOffset;
            lastChunkEnd = effectiveOffset + caption.duration;
          } else {
            bool endsWithPunc = currentMergedRaw.endsWith('.') ||
                currentMergedRaw.endsWith('!') ||
                currentMergedRaw.endsWith('?');

            bool hasLongGap = false;
            if (lastChunkEnd != null && (effectiveOffset - lastChunkEnd).inMilliseconds > 2000) {
              hasLongGap = true;
            }

            if (!endsWithPunc && !hasLongGap && currentMergedRaw.length < 50) {
              currentMergedRaw = '$currentMergedRaw $cleanedText';
              currentMergedLrc = '$currentMergedLrc $timeTag $cleanedText';
              lastChunkEnd = effectiveOffset + caption.duration;
            } else {
              flushCurrentLine();
              currentMergedRaw = cleanedText;
              currentMergedLrc = '$timeTag $cleanedText';
              currentMergedStart = effectiveOffset;
              lastChunkEnd = effectiveOffset + caption.duration;
            }
          }
        }

        flushCurrentLine();

        final typeStr = trackInfo.isAutoGenerated ? ' (Автоматичні)' : ' (Авторські)';
        var cleanLangName = trackInfo.language.name.replaceAll(' (auto-generated)', '').trim();
        final name = '$cleanLangName$typeStr';

        AppLogger.info('Generated LRC:\n${lrcBuffer.toString()}', 'YOUTUBE');

        if (!result.containsKey(name)) {
          result[name] = lrcBuffer.toString();
        }
      }

      return result.isNotEmpty ? result : null;
    } catch (e) {
      AppLogger.warning('No youtube captions found for $videoId', 'YOUTUBE');
      return null;
    }
  }
}
